### ISSUE TITLE
Issue when testing in old Debug Mode

### ISSUE THREAD

**Issue by mariuszpala** [realityforge/gwt-websockets#3]
Hi,

I've just tried to init a web socket connection with gwt-websockets library, but in the debug mode I get the exception below. I'm using GWT 2.7. Any idea what could it be? Thanks!

SEVERE: (null) @com.google.gwt.core.client.impl.Impl::apply(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)([JavaScript object(3083), JavaScript object(1046), JavaScript object(3609)]): nullcom.google.gwt.core.client.JavaScriptException: (null) @com.google.gwt.core.client.impl.Impl::apply(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)([JavaScript object(3083), JavaScript object(1046), JavaScript object(3609)]): null
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:299)
    at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:745)

**Comment by realityforge** [comment]
Sorry - I haven't used the old devmode for a long time and thus have not seen this error before. IIRC this error used to occur when you incorrectly returned an object that is not the same type as declared from jsni method. However I just eyeballed the code and it seems ok. So unfortunately I am no  help.

**Comment by realityforge** [comment]
Closing this out as the old DevMode seems largely unsupported these days.
